services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.prod
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.dev
    env_file:
      - ./.env
    environment:
      DJANGO_SETTINGS_MODULE: djangoindia.settings.production
    ports:
      - "8000:8000"
