services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=djangoindia.settings.local
